[graph]

targets = [
    # The triple can be any string, but only the target triples built in to
    # rustc (as of 1.40) can be checked against actual config expressions
    #"x86_64-unknown-linux-musl",
    # You can also specify which target_features you promise are enabled for a
    # particular target. target_features are currently not validated against
    # the actual valid features supported by the target architecture.
    #{ triple = "wasm32-unknown-unknown", features = ["atomics"] },
]
#exclude = []
all-features = true

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
version = 2
unused-allowed-license = "warn"
allow = [ # All of the below licenses are verified GPLv3 compatible
    "MIT",
    "Unicode-3.0",
    "ISC",
    "BSL-1.0",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unlicense",
    "GPL-3.0",
    "LGPL-2.1",
    "MPL-2.0",
    "Zlib",
    "CDLA-Permissive-2.0"
]
confidence-threshold = 0.8
exceptions = [

]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
# wildcards = "deny"
# allow-wildcard-paths = true
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    # "https://github.com/rust-lang/crates.io-index"
]
allow-git = []
